### ISSUE TITLE
Search Engine redirects to an empty page

### ISSUE THREAD

**Issue by tarekmorsi** [SEGUC17/codeologists#106]
1- Severity --> Medium

2- Reported by --> Tarek Morsi

3- When user selects a search item in the search engine box and click on search button, no result is showed for the user or any response.

![screenshot 62](https://cloud.githubusercontent.com/assets/25376323/25585610/4be2f0c4-2e50-11e7-82ab-76d998bf461a.png)

4- Steps to Produce The Issue:
a. open the website
b. select search item in the search engine box
c. click on the 'search' button
d. no results displayed on the next page.

5- Expected Result --> on clicking 'Search' button, the website should show all the available results that meets the entered search item.

**Comment by hossamfawzy96** [comment]
![reply](https://cloud.githubusercontent.com/assets/16638853/25585728/56da1e70-2e9c-11e7-9451-b9a863aa07c9.png)

**Comment by hossamfawzy96** [comment]
![reply222](https://cloud.githubusercontent.com/assets/16638853/25585758/7374d642-2e9c-11e7-9e1b-2cbf4f55c91c.png)

**Comment by hossamfawzy96** [comment]
if you mean the set location button, it's the server issue takes time till the result is fetched back

**Comment by tarekmorsi** [comment]
Home page search engine.

**Comment by hossamfawzy96** [comment]
![repplyyy33](https://cloud.githubusercontent.com/assets/16638853/25585855/d091981a-2e9c-11e7-89df-497decac223f.png)
this is the set loaction result

**Comment by El-Etreby** [comment]
<img width="1267" alt="screen shot 2017-05-01 at 6 49 36 pm" src="https://cloud.githubusercontent.com/assets/25392406/25586295/00baabe2-2e9f-11e7-9bb2-07553c40a25c.png">

**Comment by hossamfawzy96** [comment]
![rehabloc](https://cloud.githubusercontent.com/assets/16638853/25586364/55b1c5fe-2e9f-11e7-891e-e14f68a37839.png)
![rehabloccccc](https://cloud.githubusercontent.com/assets/16638853/25586387/6b442ca4-2e9f-11e7-94f7-c331af6a69a3.png)
these results are from the deployed version check the ip

**Comment by hossamfawzy96** [comment]
![nasrloc](https://cloud.githubusercontent.com/assets/16638853/25586441/9ee84414-2e9f-11e7-8a4c-931fe1635612.png)
![nasraerrrr](https://cloud.githubusercontent.com/assets/16638853/25586457/b4cd32c6-2e9f-11e7-8295-65de94b76093.png)

**Comment by hossamfawzy96** [comment]
![agouzaloc](https://cloud.githubusercontent.com/assets/16638853/25586518/f0e8209a-2e9f-11e7-885e-1d82eda8e1d8.png)
![agouzaarena](https://cloud.githubusercontent.com/assets/16638853/25586542/03aa2dcc-2ea0-11e7-84e0-8263959d250d.png)

**Comment by hossamfawzy96** [comment]
these are the results for the three available locations
