### ISSUE TITLE
Vue running on development mode

### ISSUE THREAD

**Issue by El-Etreby** [SEGUC17/codeologists#109]
1- Severity --> Medium

2- Reported by --> Omar El-Etreby

3- Vue is running on development mode. If Vue extension is installed on google chrome the user is able to see all informations in data, etc.

4- Steps to Produce The Issue:
a. open the website
b. open console

5- Expected Result --> Vue should be running on production mode.
<img width="1260" alt="screen shot 2017-05-01 at 7 01 45 pm" src="https://cloud.githubusercontent.com/assets/25392406/25587036/76cd929c-2ea2-11e7-9b55-a82fc075d480.png">
<img width="1276" alt="screen shot 2017-05-01 at 7 01 57 pm" src="https://cloud.githubusercontent.com/assets/25392406/25587038/770e2d0c-2ea2-11e7-88bc-fd869ce158a9.png">
<img width="469" alt="screen shot 2017-05-01 at 7 02 55 pm" src="https://cloud.githubusercontent.com/assets/25392406/25587037/7708e20c-2ea2-11e7-9bb4-9a440c94ece9.png">

**Comment by mahmoud-adel-mahmoud** [comment]
Excuse me, Where is the problem ?

**Comment by El-Etreby** [comment]
When you deploy a website you shouldn't be running 2 servers(backend and front-end) instead you should run the command 'npm run build' and copy the dist folder to your backend folder to be able to run the website in production mode. Thats an example of what i can see as a user using vue extension.
<img width="1280" alt="screen shot 2017-05-01 at 7 24 39 pm" src="https://cloud.githubusercontent.com/assets/25392406/25587440/5cdf0be8-2ea4-11e7-9c3d-7f53eaf8eaa3.png">

**Comment by mahmoud-adel-mahmoud** [comment]
As a user you can access this data.
I can't get the problem.
Is it a security concern or what?

**Comment by El-Etreby** [comment]
The app works with a debug view enabled which has higher memory consumption.

**Comment by mahmoud-adel-mahmoud** [comment]
Then your problem is not with the user ability to see all info. in data, It's with the memory consumption ?!!!!!!

**Comment by El-Etreby** [comment]
Yes, it is affecting user experience. I am sure that the user shoudnt be able to see all info however i dont know wether it affects security or not. Please check out vue deployment documentation for further information https://vuejs.org/v2/guide/deployment.html

**Comment by mahmoud-adel-mahmoud** [comment]
I thought your problem was with security.
The production mode can be handled with a single line of code
