### ISSUE TITLE
No previous button on the calendar

### ISSUE THREAD

**Issue by tarekmorsi** [SEGUC17/codeologists#110]
1- Severity --> Low

2- Reported by --> Tarek Morsi

3- If user clicks next month but then wishes to go back again, he's stuck since there is no previous button.

4- Steps to Produce The Issue:
a. open the website
b. navigate to book a game
c. once the calendar is display, click next 1 time to go to the next month.

![screenshot 67](https://cloud.githubusercontent.com/assets/25376323/25587373/a198f894-2e58-11e7-9dd1-bc8f7057101e.png)

5- Expected Result --> a previous button should be at the user's disposal to be able to navigate back and not re-do the whole booking process.

**Comment by hossamfawzy96** [comment]
it's trivial because we can not book a day that's over, and the next button wont work as it's the developers choice you can not book a time unless it's within a month

**Comment by hossamfawzy96** [comment]
it's trivial because we can not book a day that's over, and the next button wont work as it's the developers choice you can not book a time unless it's within a month

**Comment by HatemRamadan** [comment]
Players can only book within one month, since today is first of may so you can only view May's schedule and the "Next" button is disabled. 
when you press next it will not view June's calendar, however if you try tomorrow you will be able to go to next month and previous month :)
