### ISSUE TITLE
Log in first error message

### ISSUE THREAD

**Issue by El-Etreby** [SEGUC17/codeologists#113]
1- Severity --> Medium
<img width="1280" alt="screen shot 2017-05-01 at 8 28 44 pm" src="https://cloud.githubusercontent.com/assets/25392406/25589581/6e64fffe-2ead-11e7-846a-08cb48748d54.png">
<img width="1280" alt="screen shot 2017-05-01 at 8 28 49 pm" src="https://cloud.githubusercontent.com/assets/25392406/25589582/6e66af0c-2ead-11e7-9bdd-fdcaa752be36.png">

2- Reported by --> Omar El-Etreby

3- Log in first error message appeared when the user is logged in and tries to edit profile.

4- Steps to Produce The Issue:
a. open the website
b. sign in as a client
c. view profile
d. edit profile

5- Expected Result -->

**Comment by hossamfawzy96** [comment]
![edit](https://cloud.githubusercontent.com/assets/16638853/25589734/05d0d6d8-2eae-11e7-8c6e-4148f7b2bbb0.png)
![serviceprovider](https://cloud.githubusercontent.com/assets/16638853/25589746/0f782aec-2eae-11e7-873e-232aa1d72f3e.png)

Sorry but i've followed your mentioned steps as a Service Provider and as a Player but no errors appeared, and here are the screenshots....try your steps again and confirm the error

**Comment by El-Etreby** [comment]
It appeared all of a sudden and not with edit profile only but with My Bookings too, there may not be specific steps to reproduce this issue but it did occur.

**Comment by hossamfawzy96** [comment]
sorry but you have to give me a precise steps to the error, you must have done something that violates our restrictions

**Comment by El-Etreby** [comment]
The same issue occurred again now when using my bookings in client profile.

**Comment by mahmoud-adel-mahmoud** [comment]
<img width="1280" alt="screen shot 2017-05-01 at 9 33 51 pm" src="https://cloud.githubusercontent.com/assets/25283016/25591713/f1df9350-2eb5-11e7-9e23-df7aab1f0c04.png">

The only error that can happen in my bookings is when you try to cancel a book. But it seems that there is no errors here.
Please be descriptive in your steps.
