### ISSUE TITLE
Available games not show to the service provider

### ISSUE THREAD

**Issue by tarekmorsi** [SEGUC17/codeologists#114]
1- Severity --> Low 
2- Reported by --> Tarek Morsi

3- Service provider can't proceed to the available games page because 'available games' is not shown on the navigation bar.

4- Steps to Produce The Issue:
a. open the website
b. sign in as a service provider

![screenshot 71](https://cloud.githubusercontent.com/assets/25376323/25589951/671c3f9a-2e63-11e7-8b8a-6b4f38833d72.png)

5- Expected Result --> See the available games on the navigation bar.

 ̶
̶1̶-̶ ̶S̶e̶v̶e̶r̶i̶t̶y̶ ̶-̶-̶>̶ ̶M̶e̶d̶i̶u̶m̶
̶
̶2̶-̶ ̶R̶e̶p̶o̶r̶t̶e̶d̶ ̶b̶y̶ ̶-̶-̶>̶ ̶T̶a̶r̶e̶k̶ ̶M̶o̶r̶s̶i̶
̶
̶3̶-̶ ̶S̶e̶r̶v̶i̶c̶e̶ ̶p̶r̶o̶v̶i̶d̶e̶r̶ ̶c̶a̶n̶ ̶p̶r̶o̶c̶e̶e̶d̶ ̶t̶o̶ ̶t̶h̶e̶ ̶a̶v̶a̶i̶l̶a̶b̶l̶e̶ ̶g̶a̶m̶e̶s̶ ̶p̶a̶g̶e̶ ̶e̶v̶e̶n̶ ̶t̶h̶o̶u̶g̶h̶ ̶'̶a̶v̶a̶i̶l̶a̶b̶l̶e̶ ̶g̶a̶m̶e̶s̶'̶ ̶i̶s̶ ̶n̶o̶t̶ ̶s̶h̶o̶w̶n̶ ̶o̶n̶ ̶t̶h̶e̶ ̶n̶a̶v̶i̶g̶a̶t̶i̶o̶n̶ ̶b̶a̶r̶ ̶(̶w̶h̶i̶c̶h̶ ̶I̶ ̶g̶u̶e̶s̶s̶,̶ ̶m̶e̶a̶n̶s̶ ̶t̶h̶a̶t̶ ̶i̶t̶'̶s̶ ̶r̶e̶s̶t̶r̶i̶c̶t̶e̶d̶ ̶t̶o̶ ̶t̶h̶e̶ ̶p̶l̶a̶y̶e̶r̶s̶ ̶o̶n̶l̶y̶)̶ ̶a̶n̶d̶ ̶s̶e̶n̶d̶ ̶a̶ ̶r̶e̶q̶u̶e̶s̶t̶ ̶t̶o̶ ̶t̶h̶e̶ ̶p̶l̶a̶y̶e̶r̶'̶s̶ ̶g̶a̶m̶e̶.̶
̶
̶4̶-̶ ̶S̶t̶e̶p̶s̶ ̶t̶o̶ ̶P̶r̶o̶d̶u̶c̶e̶ ̶T̶h̶e̶ ̶I̶s̶s̶u̶e̶:̶
̶a̶.̶ ̶o̶p̶e̶n̶ ̶t̶h̶e̶ ̶w̶e̶b̶s̶i̶t̶e̶
̶b̶.̶ ̶s̶i̶g̶n̶ ̶i̶n̶ ̶a̶s̶ ̶a̶ ̶s̶e̶r̶v̶i̶c̶e̶ ̶p̶r̶o̶v̶i̶d̶e̶r̶
̶c̶.̶ ̶n̶a̶v̶i̶g̶a̶t̶e̶ ̶t̶o̶ ̶/̶g̶a̶m̶e̶s̶ ̶a̶s̶ ̶a̶ ̶p̶r̶o̶v̶i̶d̶e̶r̶
̶
̶!̶[̶s̶c̶r̶e̶e̶n̶s̶h̶o̶t̶ ̶7̶1̶]̶(̶h̶t̶t̶p̶s̶:̶/̶/̶c̶l̶o̶u̶d̶.̶g̶i̶t̶h̶u̶b̶u̶s̶e̶r̶c̶o̶n̶t̶e̶n̶t̶.̶c̶o̶m̶/̶a̶s̶s̶e̶t̶s̶/̶2̶5̶3̶7̶6̶3̶2̶3̶/̶2̶5̶5̶8̶9̶9̶5̶1̶/̶6̶7̶1̶c̶3̶f̶9̶a̶-̶2̶e̶6̶3̶-̶1̶1̶e̶7̶-̶8̶b̶8̶a̶-̶6̶b̶4̶f̶3̶8̶8̶3̶3̶d̶7̶2̶.̶p̶n̶g̶)̶
̶
̶5̶-̶ ̶E̶x̶p̶e̶c̶t̶e̶d̶ ̶R̶e̶s̶u̶l̶t̶ ̶-̶-̶>̶ ̶R̶e̶d̶i̶r̶e̶c̶t̶ ̶t̶o̶ ̶a̶ ̶4̶0̶4̶ ̶p̶a̶g̶e̶ ̶o̶r̶ ̶t̶o̶ ̶t̶h̶e̶ ̶l̶o̶g̶i̶n̶ ̶a̶s̶ ̶a̶ ̶p̶l̶a̶y̶e̶r̶ ̶p̶a̶g̶e̶.̶ ̶(̶a̶n̶y̶ ̶t̶y̶p̶e̶ ̶o̶f̶ ̶e̶r̶r̶o̶r̶ ̶h̶a̶n̶d̶l̶i̶n̶g̶)̶ ̶

**Comment by hossamfawzy96** [comment]
sorry, but you are assuming restrictions as if you are the website creator,the service provider can ask to join a game there is no problem in this; the available games button is not there just a mistake but no bugs are generated

**Comment by tarekmorsi** [comment]
I don't see the available games in the navigation bar?

**Comment by hossamfawzy96** [comment]
i've told you **THE AVAILABLE GAMES BUTTON IS NOT THERE JUST A MISS AND NO BUGS ARE GENERATED**

**Comment by El-Etreby** [comment]
The routes should be protected. NOTE: thats not how you are supposed to close the issue, please re-open the issue as it wasnt solved.

**Comment by hossamfawzy96** [comment]
Unauthorized access to available games as a provider was not the problem and the routes are protected, you cannot rename the issue after it's closed, and it's how we should close issues as there was not any issue with the old title
