### ISSUE TITLE
Available games is not displayed on the navigation bar

### ISSUE THREAD

**Issue by tarekmorsi** [SEGUC17/codeologists#117]
1- Severity --> Medium
2- Reported by --> Tarek Morsi

3- Service provider can't proceed to the available games page because 'available games' is not shown on the navigation bar. Only way to navigate to available games is through /games in the url.

4- Steps to Produce The Issue:
a. open the website
b. sign in as a service provider

![screenshot 71](https://cloud.githubusercontent.com/assets/25376323/25589951/671c3f9a-2e63-11e7-8b8a-6b4f38833d72.png)

5- Expected Result --> See the available games on the navigation bar.

**Comment by mahmoud-adel-mahmoud** [comment]
One of your team member has mentioned it and the answer was it was a mistake
