### ISSUE TITLE
Empty comments and buttons issue

### ISSUE THREAD

**Issue by hazemsalah** [SEGUC17/codeologists#126]
1- Severity --> Low

2- Reported by --> Hazem Salah

3- Player can add an empty comment and buttons (like, forward, share) not working

4- Steps to Produce The Issue:
a. open the website and log in as a player
b. choose an arena
c. write an empty comment with just space and try to click on the buttons

5- Expected Result --> empty comment should not be added, buttons should be working.

**Comment by OmarKharouba** [comment]
that was mentioned in another issue

**Comment by hossamfawzy96** [comment]
Eshta byl72 bs y3ml issue able l deadline 👍
