### ISSUE TITLE
Top arenas 

### ISSUE THREAD

**Issue by hazemsalah** [SEGUC17/codeologists#127]
Severity <-- low
Reported By <-- Hazem Salah
 Top arenas in the home page shows first no arenas to show then loads the top arenas 
Steps : 
A) open home page
B) navigate to top arenas

**Comment by mahmoud-adel-mahmoud** [comment]
The website takes time to load the data.
No bugs however. At the end top arenas appear.

**Comment by hazemsalah** [comment]
I think a loading sogn would be more appropriate than seeing no arenas then they appear

**Comment by hazemsalah** [comment]
Sign**

**Comment by mahmoud-adel-mahmoud** [comment]
I think it doesn't take that long time that forces us to make a loading sign.
But, eventually thank you for that we will take into consideration.
