### ISSUE TITLE
Requires login when logged in 

### ISSUE THREAD

**Issue by hazemsalah** [SEGUC17/codeologists#130]
Severity <-- medium 
Hazem 
When logged in and trying to book an error message saying needs to login appears 
Steps : 
Logging in 
Trying to book
Choosing day and time
Clicking book
Error message appears
Expecting to book normally
![img_5333](https://cloud.githubusercontent.com/assets/25356855/25597526/5c68a48c-2ecf-11e7-9c76-f123296a9d63.PNG)

**Comment by OmarKharouba** [comment]
so that's a new feature 
you are booking through create arena page :laughing:

**Comment by hazemsalah** [comment]
My bad its an error in reporting this happens when teyong to create an arena not in booking

**Comment by hazemsalah** [comment]
Trying *

**Comment by hossamfawzy96** [comment]
if the deadline isn't extended thank's for your hard work to notify us with errors.

**Comment by hazemsalah** [comment]
Its not about the deadline nor about trying to report each and every error , its about your unprofessional way to respond on our reported issues , which is either by denying it , or fixing it then replying with that there is no issue men el awel , its not about me aw el deadline i started writting issues when i saw your unprofessional way of responding to some of the team issues, i am not saying that all of your replies are unprofessional, but you do think that we are writting issues 3ashan netala3 el website wehesh we 5alas we mesh shayfeen en reporting issues dii 3ashan tesa3edko tehaseno mel website we same goes for our website btw its not graded that every team member must submit an issue before the deadline :) thank you and good luck

**Comment by hossamfawzy96** [comment]
I didnot know that my comment was so meaningful it was a thank you comment but it seems that you don't like it that's fine....btw we didnot update our deployed code since the deadline

**Comment by mahmoud-adel-mahmoud** [comment]
With all do respect we are not fixing the issues and telling you it doesn't exist from the beginning.
So, please don't accuse us and try to find real bugs that really could help.
AGAIN WE DIDN'T FIX ANYTHING AND TELL YOU IT'S WORKING FROM THE BEGINNING.
I think you should take a deeper look in the posted issues and see if most of the issues were reasonable or not.

**Comment by hazemsalah** [comment]
I am not accusing or anything , chill , anyways  god luck :)

**Comment by aabdelzaher** [comment]
- First of all about fixing the bugs then replying  .. the last commit on the repo was 2 days ago.
- About our replies we are more than happy to know bugs in our website to solve it .. and the issues that was concerning real bugs we have taken it into consideration.
About the issues:
*some of the issues was meaningless or not explained well for example "random errors while navigating"
*some issues were duplicated
*some issues has an irrelevant screenshots without proper description like taking screenshot for the console and to an irrelevant warning.
-About the professionalism we responded professionally on the real issues .. or not respond to it as they are real bugs that we took into consideration.

**Comment by hazemsalah** [comment]
They were trying to help what you see as an error might differ from what other see that's why there is a severity measure and i dont see any of them putting a highle severe issue it's either low or medium , concerning my last issues that i posted i think i clarified why i posted them , 3omoman ehna makonash no2sod netala3 el website wehesh law ento fahmeen kda , thank you :)

**Comment by hazemsalah** [comment]
Others*

**Comment by aabdelzaher** [comment]
wallahy ma fahmeen enko 3awzeen ttala3ooh w7sh wla 7aga .. ma zy manto 3amalto 3ndna e7na tala3na issues l team tani .. w m3ndnash mashakel 5ales f enko ttala3o bugs .. w zy ma oltelak el issues ely f3ln feha mashakel 3ndna makonash bn2ool 7aga 3leeha .. kol kalamna kan 3la el issues ely msh wad7a.

**Comment by hossamfawzy96** [comment]
Y3nii 7ot nfsk mkana
1- w give you steps 
2- you try the steps on your website, however no errors happen
How should you reply.....just asking for more descriptive steps and reasonable issues isn't regarded as "Nena fahmyn nko 3ayzyn tetal3o l website w7sh"

**Comment by hazemsalah** [comment]
I do understand , bas boselha men el ne7ya el tanya lama had yepost issue we yeb2a hasal ma3ah fe3lan we had ye5osh yerod ye2olo la2 ma7asalsh we mafeesh haga , We i think en we both know en el deployment 3amel mashakel ma3 nas ketir fa fee 3'alatat betehsal be sababo fahem mesh keset enena ben2ool isssues mahasaletsh momken tehsal ma3aya we a3mel refresh lel page ala2eha zabatet bas ben report el kalam da ehtyaty 3ashan momken teb2a haga ento mesh wa5deen balko menhom mesh aktar
